name: fuel_delivery_app_user
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  # Firebase
  cloud_firestore: ^4.17.2
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1

  # State Management
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5

  # Navigation
  go_router: ^14.1.1
  google_nav_bar: ^5.0.6

  # Authentication
  google_sign_in: ^6.2.1

  # Payment
  flutter_stripe: ^11.0.0
  razorpay_flutter: ^1.3.7

  # UI Components
  flutter_screenutil: ^5.9.0
  gap: ^3.0.1
  lottie: ^3.1.2
  shimmer: ^3.0.0
  cached_network_image: ^3.4.0
  carousel_slider: ^5.0.0
  google_fonts: ^6.2.1
  hugeicons: ^0.0.7

  # Utilities
  dartz: ^0.10.1
  get_it: ^7.7.0
  intl: ^0.19.0
  collection: ^1.17.0

  #Theme
  flex_color_scheme: ^8.0.2

  flutter:
    sdk: flutter
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Black.ttf
    - family: Inter-var
      fonts:
        - asset: fonts/Inter-VariableFont_slnt,wght.ttf
  assets:
      - assets/animations/
      - assets/images/
      - assets/images/car_wash/
      - assets/images/battary/
      - assets/images/deep_clean/
      - assets/images/fuel_delivery/
      - assets/images/oil_change/
      - assets/images/other_services/
      - assets/images/vechile_inspection/
      - assets/images/ev_charge/
   
      
      
  generate: true